"""
Feature extraction orchestrator for the PixFraudDetection polyglot pipeline.

This script consumes the pre-aggregated Parquet files generated by the Go Data Engine
(aggregated_edges.parquet, aggregated_nodes.parquet). It instantly constructs the 
NetworkX DiGraphs and runs the Python-native ML algorithms without the overhead 
of pandas-based relational merges and sliding window iterations.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import pandas as pd
import networkx as nx
from tqdm import tqdm

from src.config import DATA_PATH

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from src.config import (
    DATASET_SIZE,
    EVALUATION_K_VALUES,
    OUTPUT_FEATURES_FILE,
    OUTPUT_METRICS_FILE,
    RANK_ANOMALY_PERCENTILE,
    RANK_STABILITY_TOP_K,
    RUN_EVALUATION,
    RUN_LEIDEN,
    RUN_RANK_STABILITY,
)
from src.features.base import FeatureExtractor
from src.features.centrality import (
    BetweennessExtractor,
    HITSExtractor,
    PageRankFrequencyExtractor,
    PageRankVolumeExtractor,
)
from src.features.community import KCoreExtractor, LeidenCommunityExtractor
from src.features.stability import RankStabilityTracker

# ---------------------------------------------------------------------------
# Post-processing analysis
# ---------------------------------------------------------------------------

def _analyze_leiden_effectiveness(results_df: pd.DataFrame) -> None:
    print("\n" + "=" * 60)
    print("Leiden Community Detection Analysis")
    print("=" * 60)

    valid_df = results_df[results_df["leiden_id"] != -1].copy()
    if valid_df.empty:
        print("No valid Leiden communities found.")
        return

    last_date = valid_df["date"].max()
    final_df = valid_df[valid_df["date"] == last_date].copy()

    print(f"\nAnalysis based on final day: {last_date}")
    print(f"Total nodes with community assignment: {len(final_df):,}")

    n_communities = final_df["leiden_id"].nunique()
    print(f"Total communities detected: {n_communities:,}")

    community_stats = (
        final_df.groupby("leiden_id")
        .agg(
            size=("entity_id", "count"),
            fraud_count=("is_fraud", "sum"),
            fraud_rate=("is_fraud", "mean"),
        )
        .reset_index()
    )

    overall_fraud_rate = final_df["is_fraud"].mean()
    print(f"Overall fraud rate: {overall_fraud_rate:.4%}")

    print("\n[Community Size Distribution]")
    print("-" * 50)
    size_bins = [1, 2, 5, 10, 50, 100, 500, float("inf")]
    size_labels = ["1", "2-4", "5-9", "10-49", "50-99", "100-499", "500+"]

    community_stats["size_bin"] = pd.cut(
        community_stats["size"], bins=size_bins, labels=size_labels, right=False
    )

    size_analysis = (
        community_stats.groupby("size_bin", observed=True)
        .agg(
            n_communities=("leiden_id", "count"),
            total_nodes=("size", "sum"),
            total_fraud=("fraud_count", "sum"),
        )
        .reset_index()
    )

    size_analysis["fraud_rate"] = size_analysis["total_fraud"] / size_analysis["total_nodes"]
    size_analysis["lift"] = size_analysis["fraud_rate"] / overall_fraud_rate

    print(f"{'Size':<10} {'Communities':<12} {'Nodes':<10} {'Fraud':<8} {'Rate':<10} {'Lift':<8}")
    print("-" * 60)
    for _, row in size_analysis.iterrows():
        print(
            f"{row['size_bin']:<10} {int(row['n_communities']):<12} "
            f"{int(row['total_nodes']):<10} {int(row['total_fraud']):<8} "
            f"{row['fraud_rate']:.4%}   {row['lift']:.2f}x"
        )

# ---------------------------------------------------------------------------
# Main orchestrator
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 60)
    print("Graph Feature Generation Pipeline (Polyglot Mode)")
    print(f"Dataset: {DATASET_SIZE}")
    print(f"Evaluation:     {'Enabled' if RUN_EVALUATION else 'Disabled'}")
    print(f"Leiden:         {'Enabled' if RUN_LEIDEN else 'Disabled'}")
    print(f"Rank Stability: {'Enabled' if RUN_RANK_STABILITY else 'Disabled'}")
    print("=" * 60)

    # 1. Load Data Engine Outputs
    print("Loading Go Data Engine Parquet files...")
    edges_df = pd.read_parquet(DATA_PATH / "aggregated_edges.parquet")
    nodes_df = pd.read_parquet(DATA_PATH / "aggregated_nodes.parquet")
    
    # Load raw laundering data and accounts for ground truth labels
    laundering_df = pd.read_parquet(DATA_PATH / "2_filtered_laundering_transactions.parquet")
    accounts_df = pd.read_parquet(DATA_PATH / "3_filtered_accounts.parquet")

    # Map from_account and to_account to actual Entity IDs
    laundering_df = laundering_df.merge(
        accounts_df, left_on='from_account', right_on='Account Number', how='inner'
    ).rename(columns={'Entity ID': 'source_entity'}).drop(columns=['Account Number'])

    laundering_df = laundering_df.merge(
        accounts_df, left_on='to_account', right_on='Account Number', how='inner'
    ).rename(columns={'Entity ID': 'target_entity'}).drop(columns=['Account Number'])

    # Safely convert PyArrow timestamps
    if pd.api.types.is_numeric_dtype(laundering_df['timestamp']):
        laundering_df['timestamp'] = pd.to_datetime(laundering_df['timestamp'], unit='ns')
    else:
        laundering_df['timestamp'] = pd.to_datetime(laundering_df['timestamp'])
        
    laundering_df['timestamp'] = laundering_df['timestamp'].dt.tz_localize(None)

    unique_dates = sorted(edges_df['window_date'].unique())

    print(f"Loaded {len(unique_dates)} temporal windows.\n")
    
    # 2. Declare extractor strategies
    extractors: dict[str, FeatureExtractor] = {
        "pr_vol_85": PageRankVolumeExtractor(alpha=0.85),
        "pr_vol_75": PageRankVolumeExtractor(alpha=0.75),
        "pr_count": PageRankFrequencyExtractor(alpha=0.85),
        "hits": HITSExtractor(max_iter=100),
        "betweenness": BetweennessExtractor(k=50),
        "k_core": KCoreExtractor(),
    }

    if RUN_LEIDEN:
        extractors["leiden_macro"] = LeidenCommunityExtractor(resolution=1.0)
        extractors["leiden_micro"] = LeidenCommunityExtractor(resolution=2.0)

    stability_tracker = RankStabilityTracker(
        top_k=RANK_STABILITY_TOP_K,
        threshold_percentile=RANK_ANOMALY_PERCENTILE,
    )

    all_features: list[dict] = []
    all_daily_metrics: list[dict] = []
    all_rank_stability: list[dict] = []

    # 3. Process Windows
    with tqdm(total=len(unique_dates), desc="Processing days", unit="day") as pbar:
        for date_str in unique_dates:
            current_date = pd.to_datetime(date_str)
            
            window_edges = edges_df[edges_df['window_date'] == date_str]
            window_nodes = nodes_df[nodes_df['window_date'] == date_str]

            # Instantly build NetworkX Graph
            G = nx.from_pandas_edgelist(
                window_edges, 
                source='source', 
                target='target', 
                edge_attr=['weight', 'volume', 'count', 'amount_std'], 
                create_using=nx.DiGraph 
            )

            # Node stats lookup dictionary (Pyright kwargs fix)
            node_stats = window_nodes.set_index('entity_id')[['vol_sent', 'vol_recv', 'tx_count']].to_dict(orient='index')

            # Extract features
            daily_metrics: dict[str, dict] = {}
            for key, extractor in extractors.items():
                daily_metrics[key] = extractor.extract(G)

            # Rank stability
            rank_changes: dict = {}
            anomalies: set = set()
            if RUN_RANK_STABILITY:
                flat_pr_scores: dict = {
                    node: feats.get("pagerank", 0.0)
                    for node, feats in daily_metrics.get("pr_vol_85", {}).items()
                }
                stability_result = stability_tracker.compute(flat_pr_scores)

                if stability_result is not None:
                    rank_changes = stability_result["rank_changes"]
                    anomalies = stability_result["anomalies"]
                    all_rank_stability.append(
                        {
                            "date": current_date.date(),
                            "algorithm": "pr_vol_85",
                            "stability_score": stability_result["stability_score"],
                            "num_new_entrants": stability_result["num_new_entrants"],
                            "num_dropouts": stability_result["num_dropouts"],
                            "num_anomalies": stability_result["num_anomalies"],
                        }
                    )

            # Time-aware fraud labels
            cutoff_dt = pd.to_datetime(date_str)
            mask = laundering_df["timestamp"] <= cutoff_dt
            laundering_txns = laundering_df.loc[mask]
            
            bad_actors_up_to_date = set()
            if 'source_entity' in laundering_txns.columns:
                  bad_actors_up_to_date = set(laundering_txns["source_entity"]).union(set(laundering_txns["target_entity"]))

            # Compile features
            for node in G.nodes():
                ns = node_stats.get(node, {})
                vol_s = ns.get("vol_sent", 0.0)
                vol_r = ns.get("vol_recv", 0.0)

                record: dict = {
                    "date": current_date.date(),
                    "entity_id": node,
                    "pagerank_vol_85": daily_metrics.get("pr_vol_85", {}).get(node, {}).get("pagerank", 0.0),
                    "pagerank_vol_75": daily_metrics.get("pr_vol_75", {}).get(node, {}).get("pagerank", 0.0),
                    "pagerank_count": daily_metrics.get("pr_count", {}).get(node, {}).get("pagerank_count", 0.0),
                    "hits_hub": daily_metrics.get("hits", {}).get(node, {}).get("hits_hub", 0.0),
                    "hits_auth": daily_metrics.get("hits", {}).get(node, {}).get("hits_auth", 0.0),
                    "leiden_macro_id": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_id", -1),
                    "leiden_macro_size": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_size", 0),
                    "leiden_micro_id": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_id", -1),
                    "leiden_micro_size": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_size", 0),
                    "degree": G.degree(node),
                    "in_degree": G.in_degree(node),
                    "out_degree": G.out_degree(node),
                    "vol_sent": vol_s,
                    "vol_recv": vol_r,
                    "tx_count": ns.get("tx_count", 0),
                    "flow_ratio": vol_s / (vol_r + 1.0),
                    "betweenness": daily_metrics.get("betweenness", {}).get(node, {}).get("betweenness", 0.0),
                    "k_core": daily_metrics.get("k_core", {}).get(node, {}).get("k_core", 0),
                    "pagerank_rank_change": rank_changes.get(node, 0),
                    "is_rank_anomaly": 1 if node in anomalies else 0,
                    "is_fraud": 1 if node in bad_actors_up_to_date else 0,
                }
                all_features.append(record)

            if RUN_EVALUATION:
                pagerank_scores = {node: daily_metrics.get("pr_vol_85", {}).get(node, {}).get("pagerank", 0.0) for node in G.nodes()}
                hits_hubs = {node: daily_metrics.get("hits", {}).get(node, {}).get("hits_hub", 0.0) for node in G.nodes()}
                hits_auths = {node: daily_metrics.get("hits", {}).get(node, {}).get("hits_auth", 0.0) for node in G.nodes()}
                betweenness_scores = {node: daily_metrics.get("betweenness", {}).get(node, {}).get("betweenness", 0.0) for node in G.nodes()}
                k_core_scores = {node: daily_metrics.get("k_core", {}).get(node, {}).get("k_core", 0) for node in G.nodes()}

                if pagerank_scores:
                    valid_k_values = [k for k in EVALUATION_K_VALUES if k <= len(G)]
                    if valid_k_values:
                        from src.features._evaluation import compute_daily_evaluation_metrics
                        eval_metrics = compute_daily_evaluation_metrics(
                            bad_actors=bad_actors_up_to_date,
                            k_values=valid_k_values,
                            pagerank=pagerank_scores,
                            hits_hub=hits_hubs,
                            hits_auth=hits_auths,
                            betweenness=betweenness_scores,
                            k_core=k_core_scores,
                        )
                        for algo_name, algo_metrics in eval_metrics.items():
                            metric_record: dict = {
                                "date": current_date.date(),
                                "algorithm": algo_name,
                                "total_nodes": algo_metrics["total_nodes"],
                                "total_fraud": algo_metrics["total_fraud"],
                                "fraud_rate": algo_metrics["fraud_rate"],
                                "roc_auc": algo_metrics.get("roc_auc"),
                                "average_precision": algo_metrics.get("average_precision"),
                            }
                            for k in valid_k_values:
                                metric_record[f"precision_at_{k}"] = algo_metrics["precision_at_k"].get(k)
                                metric_record[f"recall_at_{k}"] = algo_metrics["recall_at_k"].get(k)
                                metric_record[f"lift_at_{k}"] = algo_metrics["lift_at_k"].get(k)
                                metric_record[f"fraud_found_at_{k}"] = algo_metrics["fraud_found_at_k"].get(k)
                            all_daily_metrics.append(metric_record)

            pbar.update(1)

    print("\nCompiling results...")
    results_df = pd.DataFrame(all_features)
    
    if results_df.empty:
        print("Warning: No features were generated!")
        return

    features_out = DATA_PATH / OUTPUT_FEATURES_FILE
    print(f"Saving features to {features_out}...")
    results_df.to_parquet(features_out, index=False)

    if RUN_EVALUATION and all_daily_metrics:
        metrics_df = pd.DataFrame(all_daily_metrics)
        metrics_path = DATA_PATH / OUTPUT_METRICS_FILE
        print(f"Saving metrics to {metrics_path}...")
        metrics_df.to_parquet(metrics_path, index=False)

        print("\n" + "=" * 60)
        print("Aggregate Evaluation Summary (Mean Across All Days)")
        print("=" * 60)

        for algo in ["pagerank", "hits_hub", "hits_auth", "k_core", "betweenness"]:
            algo_df = metrics_df[metrics_df["algorithm"] == algo]
            if algo_df.empty:
                continue

            print(f"\n[{algo.upper()}]")
            print("-" * 40)

            mean_roc = float(algo_df["roc_auc"].mean())
            mean_ap = float(algo_df["average_precision"].mean())

            if not math.isnan(mean_roc):
                print(f"  Mean ROC-AUC:            {mean_roc:.4f}")
            if not math.isnan(mean_ap):
                print(f"  Mean Average Precision:  {mean_ap:.4f}")

            print("\n  Mean Precision@K:")
            for k in EVALUATION_K_VALUES:
                col = f"precision_at_{k}"
                if col in algo_df.columns:
                    mean_prec = float(algo_df[col].mean())
                    if not math.isnan(mean_prec):
                        lift_col = f"lift_at_{k}"
                        mean_lift = (
                            float(algo_df[lift_col].mean())
                            if lift_col in algo_df.columns
                            else 0.0
                        )
                        print(f"    @{k:>5}: {mean_prec:.4%} (lift: {mean_lift:.2f}x)")

    if RUN_LEIDEN:
        leiden_analysis_df = results_df.rename(
            columns={"leiden_macro_id": "leiden_id", "leiden_macro_size": "leiden_size"}
        )
        _analyze_leiden_effectiveness(leiden_analysis_df)

    print("\n" + "=" * 60)
    print("Feature Statistics Summary")
    print("=" * 60)
    summary_cols = [
        "pagerank_vol_85",
        "pagerank_vol_75",
        "pagerank_count",
        "hits_hub",
        "hits_auth",
        "betweenness",
        "k_core",
        "degree",
        "vol_sent",
        "vol_recv",
        "tx_count",
        "flow_ratio",
        "pagerank_rank_change",
    ]
    if RUN_LEIDEN:
        summary_cols += ["leiden_macro_size", "leiden_micro_size"]

    print(results_df[[c for c in summary_cols if c in results_df.columns]].describe())

    if RUN_RANK_STABILITY and results_df["is_rank_anomaly"].sum() > 0:
        print("\n" + "=" * 60)
        print("Rank Anomaly Analysis (reference: pr_vol_85)")
        print("=" * 60)
        anomaly_df = results_df[results_df["is_rank_anomaly"] == 1]
        fraud_in_anomalies = anomaly_df["is_fraud"].sum()
        total_anomaly_flags = len(anomaly_df)
        overall_fraud_rate = results_df["is_fraud"].mean()
        anomaly_fraud_rate = (
            anomaly_df["is_fraud"].mean() if total_anomaly_flags > 0 else 0
        )

        print(f"Total rank anomaly flags: {total_anomaly_flags:,}")
        print(
            f"Fraud among rank anomalies: {fraud_in_anomalies:,} "
            f"({anomaly_fraud_rate:.2%})"
        )
        print(f"Overall fraud rate: {overall_fraud_rate:.2%}")
        if overall_fraud_rate > 0:
            print(
                f"Lift from rank anomaly detection: "
                f"{anomaly_fraud_rate / overall_fraud_rate:.2f}x"
            )

    print("\nDone!")

if __name__ == "__main__":
    main()