"""
Feature extraction orchestrator for the PixFraudDetection polyglot pipeline.

This script consumes the pre-aggregated Parquet files generated by the DuckDB Data Engine (02_aggregate_graph.sql).
It instantly constructs the 
NetworkX DiGraphs and runs the Python-native ML algorithms without the overhead 
of pandas-based relational merges and sliding window iterations.

Execution model: Map (Parallel Extraction) -> Reduce (Sequential Rank Stability)
    - Each temporal window is processed independently in a worker process via
      concurrent.futures.ProcessPoolExecutor, bypassing the Python GIL for
      CPU-bound NetworkX computations.
    - The stateful RankStabilityTracker (which compares Day T against Day T-1)
      runs sequentially after all parallel workers have completed.
"""

from __future__ import annotations

import gc
import math
import multiprocessing
import shutil
import sys
import tempfile
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import duckdb
import networkx as nx
import pandas as pd
from tqdm import tqdm

from src.config import DATA_PATH, PR_ALPHA_DEEP, PR_ALPHA_SHALLOW, PR_MAX_ITER, BETWEENNESS_K, HITS_MAX_ITER, LEIDEN_RESOLUTION_MACRO, LEIDEN_RESOLUTION_MICRO

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from src.config import (
    DATASET_SIZE,
    EVALUATION_K_VALUES,
    OUTPUT_FEATURES_FILE,
    OUTPUT_METRICS_FILE,
    RANK_ANOMALY_PERCENTILE,
    RANK_STABILITY_TOP_K,
    RUN_EVALUATION,
    RUN_LEIDEN,
    RUN_RANK_STABILITY,
)
from src.features.base import FeatureExtractor
from src.features.centrality import (
    BetweennessExtractor,
    HITSExtractor,
    PageRankFrequencyExtractor,
    PageRankVolumeExtractor,
)
from src.features.community import KCoreExtractor, LeidenCommunityExtractor
from src.features.motifs import SubgraphMotifExtractor
from src.features.stability import RankStabilityTracker


def process_window( # weirdnodes, ensemble, bank transactions papers
    date_str: str,
    edges_path: Path,
    nodes_path: Path,
    run_flags: dict,
) -> dict:
    query_edges = (
        f"SELECT * FROM read_parquet('{str(edges_path)}') "
        f"WHERE window_date = '{date_str}'"
    )
    day_edges = duckdb.query(query_edges).df()

    query_nodes = (
        f"SELECT * FROM read_parquet('{str(nodes_path)}') "
        f"WHERE window_date = '{date_str}'"
    )
    day_nodes = duckdb.query(query_nodes).df()

    if day_edges.empty or day_nodes.empty:
        del day_edges, day_nodes
        gc.collect()
        return {"date": date_str, "features": [], "metrics": [], "daily_metrics": {}}

    extractors: dict[str, FeatureExtractor] = {
        "pr_vol_deep": PageRankVolumeExtractor(alpha=PR_ALPHA_DEEP, max_iter=PR_MAX_ITER),
        "pr_vol_shallow": PageRankVolumeExtractor(alpha=PR_ALPHA_SHALLOW, max_iter=PR_MAX_ITER),
        "pr_count": PageRankFrequencyExtractor(alpha=PR_ALPHA_DEEP, max_iter=PR_MAX_ITER),
        "hits": HITSExtractor(max_iter=HITS_MAX_ITER),
        "betweenness": BetweennessExtractor(k=BETWEENNESS_K, seed=42),
        "k_core": KCoreExtractor(),
        "motifs": SubgraphMotifExtractor(fan_threshold=5, cycle_bound=5, max_degree=16, max_cycles=1000),
    }

    if run_flags.get("run_leiden", False):
        extractors["leiden_macro"] = LeidenCommunityExtractor(resolution=LEIDEN_RESOLUTION_MACRO)
        extractors["leiden_micro"] = LeidenCommunityExtractor(resolution=LEIDEN_RESOLUTION_MICRO)

    current_date = pd.to_datetime(date_str)

    G = nx.from_pandas_edgelist(
        day_edges,
        source="source",
        target="target",
        edge_attr=["weight", "volume", "count", "amount_std"],
        create_using=nx.DiGraph,
    )

    node_stat_columns = [
        "vol_sent", "vol_recv", "tx_count", "time_variance",
        "distinct_currencies_sent", "distinct_currencies_recv",
        "wire_count_sent", "wire_count_recv", 
        "cash_count_sent", "cash_count_recv",
        "bitcoin_count_sent", "bitcoin_count_recv",
        "cheque_count_sent", "cheque_count_recv",
        "credit_card_count_sent", "credit_card_count_recv",
        "ach_count_sent", "ach_count_recv",
        "reinvestment_count_sent", "reinvestment_count_recv"
    ]

    if "is_fraud" in day_nodes.columns:
        node_stat_columns.append("is_fraud")
    node_stats = day_nodes.set_index("entity_id")[node_stat_columns].to_dict(orient="index")

    daily_metrics: dict[str, dict] = {}
    for key, extractor in extractors.items():
        daily_metrics[key] = extractor.extract(G)

    bad_actors_up_to_date: set = run_flags.get("bad_actors", set()) # AMLworld, graph based anomaly survey

    features: list[dict] = []
    # Iterate over target nodes transacting today, not the historical graph nodes
    for node in day_nodes["entity_id"].unique():
        ns = node_stats.get(node, {})
        vol_s = ns.get("vol_sent", 0.0)
        vol_r = ns.get("vol_recv", 0.0)

        record: dict = {
            "date": current_date.date(),
            "entity_id": node,
            "pr_vol_deep": daily_metrics.get("pr_vol_deep", {}).get(node, {}).get("pagerank", 0.0),
            "pr_vol_shallow": daily_metrics.get("pr_vol_shallow", {}).get(node, {}).get("pagerank", 0.0),
            "pr_count": daily_metrics.get("pr_count", {}).get(node, {}).get("pagerank_count", 0.0),
            "hits_hub": daily_metrics.get("hits", {}).get(node, {}).get("hits_hub", 0.0),
            "hits_auth": daily_metrics.get("hits", {}).get(node, {}).get("hits_auth", 0.0),
            "leiden_macro_id": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_id", -1),
            "leiden_macro_size": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_size", 0),
            "leiden_macro_modularity": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_modularity", 0.0),
            "leiden_micro_id": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_id", -1),
            "leiden_micro_size": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_size", 0),
            "leiden_micro_modularity": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_modularity", 0.0),
            "degree": G.degree(node) if G.has_node(node) else 0,
            "in_degree": G.in_degree(node) if G.has_node(node) else 0,
            "out_degree": G.out_degree(node) if G.has_node(node) else 0,
            "vol_sent": vol_s,
            "vol_recv": vol_r,
            "tx_count": ns.get("tx_count", 0),
            "time_variance": ns.get("time_variance", 0.0),
            "is_fraud": int(ns.get("is_fraud", 0) or 0),
            "flow_ratio": vol_s / (vol_r if vol_r > 0 else vol_s),
            "distinct_currencies_sent": ns.get("distinct_currencies_sent", 0),
            "distinct_currencies_recv": ns.get("distinct_currencies_recv", 0),
            "wire_count_sent": ns.get("wire_count_sent", 0),
            "wire_count_recv": ns.get("wire_count_recv", 0),
            "cash_count_sent": ns.get("cash_count_sent", 0),
            "cash_count_recv": ns.get("cash_count_recv", 0),
            "bitcoin_count_sent": ns.get("bitcoin_count_sent", 0),
            "bitcoin_count_recv": ns.get("bitcoin_count_recv", 0),
            "cheque_count_sent": ns.get("cheque_count_sent", 0),
            "cheque_count_recv": ns.get("cheque_count_recv", 0),
            "credit_card_count_sent": ns.get("credit_card_count_sent", 0),
            "credit_card_count_recv": ns.get("credit_card_count_recv", 0),
            "ach_count_sent": ns.get("ach_count_sent", 0),
            "ach_count_recv": ns.get("ach_count_recv", 0),
            "reinvestment_count_sent": ns.get("reinvestment_count_sent", 0),
            "reinvestment_count_recv": ns.get("reinvestment_count_recv", 0),
            "betweenness": daily_metrics.get("betweenness", {}).get(node, {}).get("betweenness", 0.0),
            "k_core": daily_metrics.get("k_core", {}).get(node, {}).get("k_core", 0),
            "fan_out_count": daily_metrics.get("motifs", {}).get(node, {}).get("fan_out_count", 0),
            "fan_in_count": daily_metrics.get("motifs", {}).get(node, {}).get("fan_in_count", 0),
            "scatter_gather_count": daily_metrics.get("motifs", {}).get(node, {}).get("scatter_gather_count", 0),
            "gather_scatter_count": daily_metrics.get("motifs", {}).get(node, {}).get("gather_scatter_count", 0),
            "cycle_count": daily_metrics.get("motifs", {}).get(node, {}).get("cycle_count", 0),
        }
        features.append(record)

    eval_metric_records: list[dict] = []

    if run_flags.get("run_evaluation", False):
        pr_vol_deep_scores = {
            node: daily_metrics.get("pr_vol_deep", {}).get(node, {}).get("pagerank", 0.0)
            for node in G.nodes()
        }
        pr_vol_shallow_scores = {
            node: daily_metrics.get("pr_vol_shallow", {}).get(node, {}).get("pagerank", 0.0)
            for node in G.nodes()
        }
        pr_count_scores = {
            node: daily_metrics.get("pr_count", {}).get(node, {}).get("pagerank_count", 0.0)
            for node in G.nodes()
        }
        hits_hubs = {
            node: daily_metrics.get("hits", {}).get(node, {}).get("hits_hub", 0.0)
            for node in G.nodes()
        }
        hits_auths = {
            node: daily_metrics.get("hits", {}).get(node, {}).get("hits_auth", 0.0)
            for node in G.nodes()
        }
        betweenness_scores = {
            node: daily_metrics.get("betweenness", {}).get(node, {}).get("betweenness", 0.0)
            for node in G.nodes()
        }
        k_core_scores = {
            node: daily_metrics.get("k_core", {}).get(node, {}).get("k_core", 0)
            for node in G.nodes()
        }
        
        # Basic feature scores
        vol_sent_scores = {
            node: node_stats.get(node, {}).get("vol_sent", 0.0)
            for node in G.nodes()
        }
        vol_recv_scores = {
            node: node_stats.get(node, {}).get("vol_recv", 0.0)
            for node in G.nodes()
        }
        in_degree_scores = {
            node: G.in_degree(node) if G.has_node(node) else 0
            for node in G.nodes()
        }
        out_degree_scores = {
            node: G.out_degree(node) if G.has_node(node) else 0
            for node in G.nodes()
        }
        tx_count_scores = {
            node: node_stats.get(node, {}).get("tx_count", 0)
            for node in G.nodes()
        }
        time_variance_scores = {
            node: node_stats.get(node, {}).get("time_variance", 0.0)
            for node in G.nodes()
        }

        if pr_vol_deep_scores:
            evaluation_k_values = run_flags.get("evaluation_k_values", [])
            valid_k_values = [k for k in evaluation_k_values if k <= len(G)]
            if valid_k_values:
                from src.features._evaluation import compute_daily_evaluation_metrics

                eval_metrics = compute_daily_evaluation_metrics(
                    bad_actors=bad_actors_up_to_date,
                    k_values=valid_k_values,
                    pr_vol_deep=pr_vol_deep_scores,
                    pr_vol_shallow=pr_vol_shallow_scores,
                    pr_count=pr_count_scores,
                    hits_hub=hits_hubs,
                    hits_auth=hits_auths,
                    betweenness=betweenness_scores,
                    k_core=k_core_scores,
                    vol_sent=vol_sent_scores,
                    vol_recv=vol_recv_scores,
                    in_degree=in_degree_scores,
                    out_degree=out_degree_scores,
                    tx_count=tx_count_scores,
                    time_variance=time_variance_scores,
                )
                for algo_name, algo_metrics in eval_metrics.items():
                    metric_record: dict = {
                        "date": current_date.date(),
                        "algorithm": algo_name,
                        "total_nodes": algo_metrics["total_nodes"],
                        "total_fraud": algo_metrics["total_fraud"],
                        "fraud_rate": algo_metrics["fraud_rate"],
                        "roc_auc": algo_metrics.get("roc_auc"),
                        "average_precision": algo_metrics.get("average_precision"),
                    }
                    for k in valid_k_values:
                        metric_record[f"precision_at_{k}"] = algo_metrics["precision_at_k"].get(k)
                        metric_record[f"recall_at_{k}"] = algo_metrics["recall_at_k"].get(k)
                        metric_record[f"lift_at_{k}"] = algo_metrics["lift_at_k"].get(k)
                        metric_record[f"fraud_found_at_{k}"] = algo_metrics["fraud_found_at_k"].get(k)
                    eval_metric_records.append(metric_record)

    # ---- All centrality metrics for WeirdNodes ensemble stability step -----
    result = {
        "date": date_str,
        "features": features,
        "metrics": eval_metric_records,
        "daily_metrics": daily_metrics,
    }

    del G, day_edges, day_nodes, node_stats, daily_metrics
    gc.collect()

    return result


def _analyze_leiden_effectiveness(results_df: pd.DataFrame) -> None:
    print("\n" + "=" * 60)
    print("Leiden Community Detection Analysis")
    print("=" * 60)

    valid_df = results_df[results_df["leiden_id"] != -1].copy()
    if valid_df.empty:
        print("No valid Leiden communities found.")
        return

    last_date = valid_df["date"].max()
    final_df = valid_df[valid_df["date"] == last_date].copy()

    print(f"\nAnalysis based on final day: {last_date}")
    print(f"Total nodes with community assignment: {len(final_df):,}")

    n_communities = final_df["leiden_id"].nunique()
    print(f"Total communities detected: {n_communities:,}")

    community_stats = (
        final_df.groupby("leiden_id")
        .agg(
            size=("entity_id", "count"),
            fraud_count=("is_fraud", "sum"),
            fraud_rate=("is_fraud", "mean"),
        )
        .reset_index()
    )

    overall_fraud_rate = final_df["is_fraud"].mean()
    print(f"Overall fraud rate: {overall_fraud_rate:.4%}")

    print("\n[Community Size Distribution]")
    print("-" * 50)
    size_bins = [1, 2, 5, 10, 50, 100, 500, float("inf")]
    size_labels = ["1", "2-4", "5-9", "10-49", "50-99", "100-499", "500+"]

    community_stats["size_bin"] = pd.cut(
        community_stats["size"], bins=size_bins, labels=size_labels, right=False
    )

    size_analysis = (
        community_stats.groupby("size_bin", observed=True)
        .agg(
            n_communities=("leiden_id", "count"),
            total_nodes=("size", "sum"),
            total_fraud=("fraud_count", "sum"),
        )
        .reset_index()
    )

    size_analysis["fraud_rate"] = size_analysis["total_fraud"] / size_analysis["total_nodes"]
    size_analysis["lift"] = size_analysis["fraud_rate"] / overall_fraud_rate

    print(f"{'Size':<10} {'Communities':<12} {'Nodes':<10} {'Fraud':<8} {'Rate':<10} {'Lift':<8}")
    print("-" * 60)
    for _, row in size_analysis.iterrows():
        print(
            f"{row['size_bin']:<10} {int(row['n_communities']):<12} "
            f"{int(row['total_nodes']):<10} {int(row['total_fraud']):<8} "
            f"{row['fraud_rate']:.4%}   {row['lift']:.2f}x"
        )

    print("\n[Top 10 Communities by Fraud Rate (min 3 members)]")
    print("-" * 70)

    significant_communities = community_stats[community_stats["size"] >= 3].copy()
    top_fraud_communities = significant_communities.nlargest(10, "fraud_rate")

    print(f"{'Comm ID':<10} {'Size':<8} {'Fraud':<8} {'Rate':<12} {'Lift':<8}")
    print("-" * 50)
    for _, row in top_fraud_communities.iterrows():
        lift = row["fraud_rate"] / overall_fraud_rate if overall_fraud_rate > 0 else 0
        print(
            f"{int(row['leiden_id']):<10} {int(row['size']):<8} "
            f"{int(row['fraud_count']):<8} {row['fraud_rate']:.4%}      {lift:.2f}x"
        )

    pure_fraud_communities = community_stats[
        (community_stats["fraud_rate"] == 1.0) & (community_stats["size"] >= 2)
    ]

    if not pure_fraud_communities.empty:
        print("\n[Potential Fraud Rings: 100% Fraud Communities (size >= 2)]")
        print("-" * 50)
        print(
            f"Found {len(pure_fraud_communities)} communities that are 100% fraudulent"
        )
        print(
            f"Total nodes in these communities: "
            f"{pure_fraud_communities['size'].sum():,}"
        )
        print(
            f"Size distribution: {pure_fraud_communities['size'].describe().to_dict()}"
        )

    print("\n[Leiden Effectiveness Summary]")
    print("-" * 50)

    if "leiden_modularity" in valid_df.columns:
        mean_modularity = valid_df["leiden_modularity"].mean()
        print(f"Mean Leiden Modularity (Q): {mean_modularity:.4f}")


    small_community_threshold = 10
    small_communities = final_df[final_df["leiden_size"] <= small_community_threshold]
    fraud_in_small = small_communities["is_fraud"].sum()
    total_fraud = final_df["is_fraud"].sum()

    if total_fraud > 0:
        pct_fraud_in_small = fraud_in_small / total_fraud
        print(
            f"Fraud in small communities (size <= {small_community_threshold}): "
            f"{fraud_in_small:,} / {total_fraud:,} ({pct_fraud_in_small:.2%})"
        )

    avg_community_fraud_rate = community_stats["fraud_rate"].mean()
    print(f"Average community fraud rate: {avg_community_fraud_rate:.4%}")
    print(f"Overall fraud rate: {overall_fraud_rate:.4%}")

    high_fraud_communities = community_stats[
        community_stats["fraud_rate"] > overall_fraud_rate * 2
    ]
    if not high_fraud_communities.empty:
        fraud_in_high = high_fraud_communities["fraud_count"].sum()
        if total_fraud > 0:
            print(
                f"Fraud in high-concentration communities (>2x avg rate): "
                f"{fraud_in_high:,} / {total_fraud:,} "
                f"({fraud_in_high / total_fraud:.2%})"
            )


def main() -> None:
    print("=" * 60)
    print("Graph Feature Generation Pipeline")
    print(f"Dataset: {DATASET_SIZE}")
    print(f"Evaluation:     {'Enabled' if RUN_EVALUATION else 'Disabled'}")
    print(f"Leiden:         {'Enabled' if RUN_LEIDEN else 'Disabled'}")
    print(f"Rank Stability: {'Enabled' if RUN_RANK_STABILITY else 'Disabled'}")
    print("=" * 60)

    edges_path = DATA_PATH / "lookback_edges.parquet"
    nodes_path = DATA_PATH / "target_nodes.parquet" 
    transactions_path = DATA_PATH / "1_filtered_transactions.parquet"
    accounts_path = DATA_PATH / "2_filtered_accounts.parquet"
    features_out = DATA_PATH / OUTPUT_FEATURES_FILE
    feature_chunks_dir = Path(tempfile.mkdtemp(prefix="feature_chunks_"))

    def _quote_ident(identifier: str) -> str:
        return '"' + identifier.replace('"', '""') + '"'

    con = duckdb.connect()

    print("Extracting unique temporal windows...")
    unique_dates_df = con.execute(
        f"""
        SELECT DISTINCT CAST(window_date AS DATE) AS window_date
        FROM read_parquet('{edges_path}')
        ORDER BY window_date
        """
    ).df()
    unique_dates = unique_dates_df["window_date"].astype(str).tolist()
    del unique_dates_df
    gc.collect()

    print(f"Found {len(unique_dates)} windows to process.")
    if not unique_dates:
        print("No windows found. Nothing to process.")
        shutil.rmtree(feature_chunks_dir, ignore_errors=False)
        con.close()
        return

    date_bad_actors: dict[str, set] = {}
    if RUN_EVALUATION:
        print("Pre-computing per-window fraud labels with DuckDB...")
        for date_str in unique_dates:
            bad_actor_df = con.execute(
                f"""
                WITH laundering_entities AS (
                    SELECT
                        COALESCE(
                            TRY_CAST(tx.timestamp AS TIMESTAMP),
                            TO_TIMESTAMP(TRY_CAST(tx.timestamp AS DOUBLE) / 1000000000.0)
                        ) AS tx_timestamp,
                        CAST(a_from."Entity ID" AS VARCHAR) AS source_entity,
                        CAST(a_to."Entity ID" AS VARCHAR) AS target_entity
                    FROM read_parquet('{transactions_path}') tx
                    INNER JOIN read_parquet('{accounts_path}') a_from
                        ON CAST(tx.from_account AS VARCHAR) = CAST(a_from."Account Number" AS VARCHAR)
                    INNER JOIN read_parquet('{accounts_path}') a_to
                        ON CAST(tx.to_account AS VARCHAR) = CAST(a_to."Account Number" AS VARCHAR)
                    WHERE tx.is_laundering = 1
                )
                SELECT DISTINCT entity_id
                FROM (
                    SELECT source_entity AS entity_id
                    FROM laundering_entities
                    WHERE tx_timestamp <= CAST(? AS TIMESTAMP)
                    UNION ALL
                    SELECT target_entity AS entity_id
                    FROM laundering_entities
                    WHERE tx_timestamp <= CAST(? AS TIMESTAMP)
                )
                WHERE entity_id IS NOT NULL
                """,
                [date_str, date_str],
            ).df()
            date_bad_actors[date_str] = set(bad_actor_df["entity_id"].tolist())
            del bad_actor_df
            gc.collect()

    run_flags_base: dict = {
        "run_evaluation": RUN_EVALUATION,
        "run_leiden": RUN_LEIDEN,
        "evaluation_k_values": list(EVALUATION_K_VALUES),
    }

    max_workers = 3
    print(f"Launching ProcessPoolExecutor with {max_workers} workers...\n")
    print(f"WeirdNodes and motifs")

    all_daily_metrics: list[dict] = []
    written_chunk_files = 0
    daily_metrics_store: dict[str, dict] = {}  # Store daily_metrics by date for stability tracking

    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures: dict = {}
        for date_str in unique_dates:
            run_flags = {
                **run_flags_base,
                "bad_actors": date_bad_actors.get(date_str, set()),
            }
            future = executor.submit(
                process_window,
                date_str,
                edges_path,
                nodes_path,
                run_flags,
            )
            futures[future] = date_str

        with tqdm(total=len(unique_dates), desc="Processing days", unit="day") as pbar:
            for future in as_completed(futures):
                try:
                    result = future.result()  # propagates worker exceptions

                    if result["features"]:
                        feature_df = pd.DataFrame(result["features"])
                        chunk_path = feature_chunks_dir / f"features_{result['date']}.parquet"
                        feature_df.to_parquet(chunk_path, index=False)
                        written_chunk_files += 1
                        del feature_df

                    if RUN_EVALUATION and result["metrics"]:
                        all_daily_metrics.extend(result["metrics"])
                    
                    # Store daily_metrics for rank stability (if enabled)
                    if RUN_RANK_STABILITY and result["daily_metrics"]:
                        daily_metrics_store[result["date"]] = result["daily_metrics"]

                    del result
                    gc.collect()
                except Exception as exc:
                    print(f"Day generated an exception: {exc}")
                pbar.update(1)

    if written_chunk_files == 0:
        print("Warning: No features were generated!")
        shutil.rmtree(feature_chunks_dir, ignore_errors=False)
        con.close()
        return

    stability_tmp_file: Path | None = None

    if RUN_RANK_STABILITY:
        print("\nApplying WeirdNodes ensemble rank stability post-processing...")
        
        stability_tracker = RankStabilityTracker(
            top_k=RANK_STABILITY_TOP_K,
            threshold_percentile=RANK_ANOMALY_PERCENTILE,
        )
        stability_rows: list[dict] = []

        # Process windows sequentially in chronological order
        for date_str in unique_dates:
            current_metrics = daily_metrics_store.get(date_str, {})
            if not current_metrics:
                continue

            stability_result = stability_tracker.compute(current_metrics)
            if stability_result is None:
                continue

            # Capture the continuous scores
            weirdness_scores: dict = stability_result["weirdness_scores"]
            ensemble_residuals: dict = stability_result["ensemble_residuals"]
            
            # Log validation summary for this window
            validation_summary = stability_result.get("validation_summary", {})
            valid_metrics = stability_result.get("valid_metrics", [])
            if validation_summary:
                print(f"\n[{date_str}] Validation Summary:")
                for metric, stats in validation_summary.items():
                    status = "✓ VALID" if stats["valid"] else "✗ INVALID"
                    print(f"  {metric:<20} {status:<10} (ρ={stats['spearman']:.3f}, τ={stats['kendall']:.3f})")
                print(f"  Valid metrics for ensemble: {', '.join(valid_metrics) if valid_metrics else 'None'}")

            # Create stability rows for all nodes in this window
            # Get all unique nodes from the feature chunks for this date
            date_nodes_df = con.execute(
                f"""
                SELECT DISTINCT entity_id
                FROM read_parquet('{feature_chunks_dir / f"features_{date_str}.parquet"}')
                """
            ).df()
            
            # Create rows for the feature table with continuous WeirdNodes signals
            for entity_id in date_nodes_df["entity_id"]:
                stability_rows.append(
                    {
                        "window_date": pd.to_datetime(date_str).date(),
                        "entity_id": entity_id,
                        # The continuous WeirdNodes signal (magnitude of rank instability)
                        "weirdnodes_magnitude": weirdness_scores.get(entity_id, 0.0),
                        # Signed residual for interpretation
                        "weirdnodes_residual": ensemble_residuals.get(entity_id, 0.0),
                        # Directional flags (useful for identifying Black Holes vs Ghosts)
                        "is_riser": 1 if ensemble_residuals.get(entity_id, 0.0) > 0 else 0,
                        "is_faller": 1 if ensemble_residuals.get(entity_id, 0.0) < 0 else 0,
                    }
                )
            
            del date_nodes_df

        if stability_rows:
            stability_temp_dir = Path(tempfile.mkdtemp(prefix="rank_stability_"))
            stability_tmp_file = stability_temp_dir / "rank_stability.parquet"
            stability_df = pd.DataFrame(stability_rows)
            stability_df.to_parquet(stability_tmp_file, index=False)
            del stability_df
            print(f"\nRank stability features generated: {len(stability_rows):,} records")

        # Clean up daily_metrics_store to free memory
        del daily_metrics_store
        gc.collect()

    print("\nUsing pre-aggregated is_fraud labels from aggregated_nodes.parquet...")

    stability_join = ""
    stability_select = (
        "0::DOUBLE AS weirdnodes_magnitude,\n"
        "                0::DOUBLE AS weirdnodes_residual,\n"
        "                0::INTEGER AS is_riser,\n"
        "                0::INTEGER AS is_faller"
    )
    if stability_tmp_file is not None and stability_tmp_file.exists():
        stability_join = (
            f"LEFT JOIN read_parquet('{stability_tmp_file}') s\n"
            f"            ON CAST(f.date AS DATE) = CAST(s.window_date AS DATE)\n"
            f"            AND CAST(f.entity_id AS VARCHAR) = CAST(s.entity_id AS VARCHAR)"
        )
        stability_select = (
            "COALESCE(s.weirdnodes_magnitude, 0.0) AS weirdnodes_magnitude,\n"
            "                COALESCE(s.weirdnodes_residual, 0.0) AS weirdnodes_residual,\n"
            "                COALESCE(s.is_riser, 0) AS is_riser,\n"
            "                COALESCE(s.is_faller, 0) AS is_faller"
        )

    print(f"Saving features to {features_out} via DuckDB out-of-core join...")
    con.execute(
        f"""
        COPY (
            SELECT
                f.*,
                {stability_select}
            FROM read_parquet('{feature_chunks_dir / "*.parquet"}') f
            {stability_join}
        ) TO '{features_out}' (FORMAT PARQUET);
        """
    )

    print("Cleaning temporary artifacts...")
    shutil.rmtree(feature_chunks_dir, ignore_errors=False)
    if stability_tmp_file is not None and stability_tmp_file.exists():
        shutil.rmtree(stability_tmp_file.parent, ignore_errors=False)

    if RUN_EVALUATION and all_daily_metrics:
        metrics_df = pd.DataFrame(all_daily_metrics)
        metrics_path = DATA_PATH / OUTPUT_METRICS_FILE
        print(f"Saving metrics to {metrics_path}...")
        metrics_df.to_parquet(metrics_path, index=False)

        print("\n" + "=" * 60)
        print("Aggregate Evaluation Summary (Mean & Median Across All Days)")
        print("=" * 60)

        for algo in ["pr_vol_deep", "pr_vol_shallow", "pr_count", "hits_hub", "hits_auth", "k_core", "betweenness", 
                     "vol_sent", "vol_recv", "in_degree", "out_degree", "tx_count", "time_variance"]:
            algo_df = metrics_df[metrics_df["algorithm"] == algo]
            if algo_df.empty:
                continue

            print(f"\n[{algo.upper()}]")
            print("-" * 40)

            mean_roc = float(algo_df["roc_auc"].mean())
            median_roc = float(algo_df["roc_auc"].median())
            mean_ap = float(algo_df["average_precision"].mean())
            median_ap = float(algo_df["average_precision"].median())

            if not math.isnan(mean_roc):
                print(f"  Mean ROC-AUC:            {mean_roc:.4f}")
            if not math.isnan(median_roc):
                print(f"  Median ROC-AUC:          {median_roc:.4f}")
            if not math.isnan(mean_ap):
                print(f"  Mean Average Precision:  {mean_ap:.4f}")
            if not math.isnan(median_ap):
                print(f"  Median Average Precision:{median_ap:.4f}")

            print("\n  Mean Precision@K:")
            for k in EVALUATION_K_VALUES:
                col = f"precision_at_{k}"
                if col in algo_df.columns:
                    mean_prec = float(algo_df[col].mean())
                    if not math.isnan(mean_prec):
                        lift_col = f"lift_at_{k}"
                        mean_lift = (
                            float(algo_df[lift_col].mean())
                            if lift_col in algo_df.columns
                            else 0.0
                        )
                        print(f"    @{k:>5}: {mean_prec:.4%} (lift: {mean_lift:.2f}x)")

            print("\n  Median Precision@K:")
            for k in EVALUATION_K_VALUES:
                col = f"precision_at_{k}"
                if col in algo_df.columns:
                    median_prec = float(algo_df[col].median())
                    if not math.isnan(median_prec):
                        lift_col = f"lift_at_{k}"
                        median_lift = (
                            float(algo_df[lift_col].median())
                            if lift_col in algo_df.columns
                            else 0.0
                        )
                        print(f"    @{k:>5}: {median_prec:.4%} (lift: {median_lift:.2f}x)")

    if RUN_LEIDEN:
        final_columns = set(
            con.execute(
                f"SELECT * FROM read_parquet('{features_out}') LIMIT 1"
            ).df().columns
        )
        required_leiden_cols = {
            "date",
            "entity_id",
            "leiden_macro_id",
            "leiden_macro_size",
            "leiden_macro_modularity",
            "is_fraud",
        }
        if required_leiden_cols.issubset(final_columns):
            leiden_analysis_df = con.execute(
                f"""
                SELECT
                    date,
                    entity_id,
                    leiden_macro_id AS leiden_id,
                    leiden_macro_size AS leiden_size,
                    leiden_macro_modularity AS leiden_modularity,
                    is_fraud
                FROM read_parquet('{features_out}')
                """
            ).df()
            _analyze_leiden_effectiveness(leiden_analysis_df)
            del leiden_analysis_df
            gc.collect()

    print("\n" + "=" * 60)
    print("Feature Statistics Summary")
    print("=" * 60)
    summary_cols = [
        "pr_vol_deep",
        "pr_vol_shallow",
        "pr_count",
        "hits_hub",
        "hits_auth",
        "betweenness",
        "k_core",
        "degree",
        "vol_sent",
        "vol_recv",
        "tx_count",
        "time_variance",
        "flow_ratio",
        "pagerank_rank_change",
        "fan_out_count",
        "fan_in_count",
        "scatter_gather_count",
        "gather_scatter_count",
        "cycle_count",
        "cycle_count",
        "distinct_currencies_sent",
        "distinct_currencies_recv",
        "wire_count_sent", 
        "wire_count_recv", "cash_count_sent", "cash_count_recv", "bitcoin_count_sent", 
        "bitcoin_count_recv",
        "cheque_count_sent", "cheque_count_recv",
        "credit_card_count_sent", "credit_card_count_recv",
        "ach_count_sent", "ach_count_recv",
        "reinvestment_count_sent", "reinvestment_count_recv"
    ]
    if RUN_LEIDEN:
        summary_cols += ["leiden_macro_size", "leiden_micro_size", "leiden_macro_modularity", "leiden_micro_modularity"]

    output_columns = set(
        con.execute(f"SELECT * FROM read_parquet('{features_out}') LIMIT 1").df().columns
    )
    selected_summary_cols = [c for c in summary_cols if c in output_columns]
    if selected_summary_cols:
        summary_df = con.execute(
            f"""
            SELECT {", ".join(_quote_ident(c) for c in selected_summary_cols)}
            FROM read_parquet('{features_out}')
            """
        ).df()
        print(summary_df.describe())
        del summary_df
        gc.collect()

    if RUN_RANK_STABILITY and {"is_rank_anomaly", "is_fraud"}.issubset(output_columns):
        anomaly_stats = con.execute(
            f"""
            SELECT
                SUM(CASE WHEN is_rank_anomaly = 1 THEN 1 ELSE 0 END) AS total_anomaly_flags,
                SUM(CASE WHEN is_rank_anomaly = 1 THEN CAST(is_fraud AS DOUBLE) ELSE 0 END) AS fraud_in_anomalies,
                AVG(CAST(is_fraud AS DOUBLE)) AS overall_fraud_rate,
                AVG(CASE WHEN is_rank_anomaly = 1 THEN CAST(is_fraud AS DOUBLE) END) AS anomaly_fraud_rate
            FROM read_parquet('{features_out}')
            """
        ).df().iloc[0]
        total_anomaly_flags = int(anomaly_stats["total_anomaly_flags"] or 0)
        fraud_in_anomalies = float(anomaly_stats["fraud_in_anomalies"] or 0.0)
        overall_fraud_rate = float(anomaly_stats["overall_fraud_rate"] or 0.0)
        anomaly_fraud_rate = float(anomaly_stats["anomaly_fraud_rate"] or 0.0)

        if total_anomaly_flags > 0:
            print("\n" + "=" * 60)
            print("Rank Anomaly Analysis (reference: pr_vol_deep)")
            print("=" * 60)
            print(f"Total rank anomaly flags: {total_anomaly_flags:,}")
            print(
                f"Fraud among rank anomalies: {fraud_in_anomalies:,.0f} "
                f"({anomaly_fraud_rate:.2%})"
            )
            print(f"Overall fraud rate: {overall_fraud_rate:.2%}")
            if overall_fraud_rate > 0:
                print(
                    f"Lift from rank anomaly detection: "
                    f"{anomaly_fraud_rate / overall_fraud_rate:.2f}x"
                )

    con.close()

    if RUN_RANK_STABILITY:
        print("\n" + "=" * 60)
        print("Rank Stability Processing")
        print("=" * 60)
        print("Rank stability features were materialized via out-of-core DuckDB joins.")

    print("\nDone!")


if __name__ == "__main__":
    main()
