"""
Feature extraction orchestrator for the PixFraudDetection polyglot pipeline.

This script consumes the pre-aggregated Parquet files generated by the DuckDB Data Engine (02_aggregate_graph.sql).
It instantly constructs the 
NetworkX DiGraphs and runs the Python-native ML algorithms without the overhead 
of pandas-based relational merges and sliding window iterations.

Execution model: Map (Parallel Extraction) -> Reduce (Sequential Rank Stability)
    - Each temporal window is processed independently in a worker process via
      concurrent.futures.ProcessPoolExecutor, bypassing the Python GIL for
      CPU-bound NetworkX computations.
    - The stateful RankStabilityTracker (which compares Day T against Day T-1)
      runs sequentially after all parallel workers have completed.
"""

from __future__ import annotations

import gc
import math
import multiprocessing
import sys
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import duckdb
import networkx as nx
import pandas as pd
from tqdm import tqdm

from src.config import DATA_PATH, PR_ALPHA_DEEP, PR_ALPHA_SHALLOW, PR_MAX_ITER, BETWEENNESS_K, HITS_MAX_ITER, LEIDEN_RESOLUTION_MACRO, LEIDEN_RESOLUTION_MICRO

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from src.config import (
    DATASET_SIZE,
    EVALUATION_K_VALUES,
    OUTPUT_FEATURES_FILE,
    OUTPUT_METRICS_FILE,
    RANK_ANOMALY_PERCENTILE,
    RANK_STABILITY_TOP_K,
    RUN_EVALUATION,
    RUN_LEIDEN,
    RUN_RANK_STABILITY,
)
from src.features.base import FeatureExtractor
from src.features.centrality import (
    BetweennessExtractor,
    HITSExtractor,
    PageRankFrequencyExtractor,
    PageRankVolumeExtractor,
)
from src.features.community import KCoreExtractor, LeidenCommunityExtractor
from src.features.stability import RankStabilityTracker


# ---------------------------------------------------------------------------
# Top-level worker function (must be picklable for ProcessPoolExecutor)
# ---------------------------------------------------------------------------

def process_window(
    date_str: str,
    edges_path: Path,
    nodes_path: Path,
    run_flags: dict,
) -> dict:
    """
    Worker function that loads only a single day of data from disk into RAM.
    """
    # 1. Disk-stream only rows matching this date via DuckDB's out-of-core engine
    query_edges = (
        f"SELECT * FROM read_parquet('{str(edges_path)}') "
        f"WHERE window_date = '{date_str}'"
    )
    day_edges = duckdb.query(query_edges).df()

    query_nodes = (
        f"SELECT * FROM read_parquet('{str(nodes_path)}') "
        f"WHERE window_date = '{date_str}'"
    )
    day_nodes = duckdb.query(query_nodes).df()

    if day_edges.empty or day_nodes.empty:
        del day_edges, day_nodes
        gc.collect()
        return {"date": date_str, "features": [], "metrics": [], "pr_scores": {}}

    # ---- Instantiate extractors locally (picklability guarantee) ----------
    extractors: dict[str, FeatureExtractor] = {
        "pr_vol_deep": PageRankVolumeExtractor(alpha=PR_ALPHA_DEEP, max_iter=PR_MAX_ITER),
        "pr_vol_shallow": PageRankVolumeExtractor(alpha=PR_ALPHA_SHALLOW, max_iter=PR_MAX_ITER),
        "pr_count": PageRankFrequencyExtractor(alpha=PR_ALPHA_DEEP, max_iter=PR_MAX_ITER),
        "hits": HITSExtractor(max_iter=HITS_MAX_ITER),
        "betweenness": BetweennessExtractor(k=BETWEENNESS_K, seed=42),
        "k_core": KCoreExtractor(),
    }

    if run_flags.get("run_leiden", False):
        extractors["leiden_macro"] = LeidenCommunityExtractor(resolution=LEIDEN_RESOLUTION_MACRO)
        extractors["leiden_micro"] = LeidenCommunityExtractor(resolution=LEIDEN_RESOLUTION_MICRO)

    current_date = pd.to_datetime(date_str)

    # ---- Build NetworkX DiGraph ------------------------------------------
    G = nx.from_pandas_edgelist(
        day_edges,
        source="source",
        target="target",
        edge_attr=["weight", "volume", "count", "amount_std"],
        create_using=nx.DiGraph,
    )

    # ---- Node stats lookup -----------------------------------------------
    node_stats = (
        day_nodes.set_index("entity_id")[["vol_sent", "vol_recv", "tx_count", "time_variance"]]
        .to_dict(orient="index")
    )

    # ---- Run all extractors ----------------------------------------------
    daily_metrics: dict[str, dict] = {}
    for key, extractor in extractors.items():
        daily_metrics[key] = extractor.extract(G)

    # ---- Retrieve pre-computed fraud labels ------------------------------
    bad_actors_up_to_date: set = run_flags.get("bad_actors", set())

    # ---- Compile per-node features (rank stability = placeholder 0) ------
    features: list[dict] = []
    for node in G.nodes():
        ns = node_stats.get(node, {})
        vol_s = ns.get("vol_sent", 0.0)
        vol_r = ns.get("vol_recv", 0.0)

        record: dict = {
            "date": current_date.date(),
            "entity_id": node,
            "pr_vol_deep": daily_metrics.get("pr_vol_deep", {}).get(node, {}).get("pagerank", 0.0),
            "pr_vol_shallow": daily_metrics.get("pr_vol_shallow", {}).get(node, {}).get("pagerank", 0.0),
            "pr_count": daily_metrics.get("pr_count", {}).get(node, {}).get("pagerank_count", 0.0),
            "hits_hub": daily_metrics.get("hits", {}).get(node, {}).get("hits_hub", 0.0),
            "hits_auth": daily_metrics.get("hits", {}).get(node, {}).get("hits_auth", 0.0),
            "leiden_macro_id": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_id", -1),
            "leiden_macro_size": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_size", 0),
            "leiden_macro_modularity": daily_metrics.get("leiden_macro", {}).get(node, {}).get("leiden_modularity", 0.0),
            "leiden_micro_id": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_id", -1),
            "leiden_micro_size": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_size", 0),
            "leiden_micro_modularity": daily_metrics.get("leiden_micro", {}).get(node, {}).get("leiden_modularity", 0.0),
            "degree": G.degree(node),
            "in_degree": G.in_degree(node),
            "out_degree": G.out_degree(node),
            "vol_sent": vol_s,
            "vol_recv": vol_r,
            "tx_count": ns.get("tx_count", 0),
            "time_variance": ns.get("time_variance", 0.0),
            "flow_ratio": vol_s / (vol_r + 1.0),
            "betweenness": daily_metrics.get("betweenness", {}).get(node, {}).get("betweenness", 0.0),
            "k_core": daily_metrics.get("k_core", {}).get(node, {}).get("k_core", 0),
            # Placeholders — will be overwritten during sequential post-processing
            "pagerank_rank_change": 0,
            "is_rank_anomaly": 0,
            "is_fraud": 1 if node in bad_actors_up_to_date else 0,
        }
        features.append(record)

    # ---- Evaluation metrics ----------------------------------------------
    eval_metric_records: list[dict] = []

    if run_flags.get("run_evaluation", False):
        pr_vol_deep_scores = {
            node: daily_metrics.get("pr_vol_deep", {}).get(node, {}).get("pagerank", 0.0)
            for node in G.nodes()
        }
        pr_vol_shallow_scores = {
            node: daily_metrics.get("pr_vol_shallow", {}).get(node, {}).get("pagerank", 0.0)
            for node in G.nodes()
        }
        pr_count_scores = {
            node: daily_metrics.get("pr_count", {}).get(node, {}).get("pagerank_count", 0.0)
            for node in G.nodes()
        }
        hits_hubs = {
            node: daily_metrics.get("hits", {}).get(node, {}).get("hits_hub", 0.0)
            for node in G.nodes()
        }
        hits_auths = {
            node: daily_metrics.get("hits", {}).get(node, {}).get("hits_auth", 0.0)
            for node in G.nodes()
        }
        betweenness_scores = {
            node: daily_metrics.get("betweenness", {}).get(node, {}).get("betweenness", 0.0)
            for node in G.nodes()
        }
        k_core_scores = {
            node: daily_metrics.get("k_core", {}).get(node, {}).get("k_core", 0)
            for node in G.nodes()
        }

        if pr_vol_deep_scores:
            evaluation_k_values = run_flags.get("evaluation_k_values", [])
            valid_k_values = [k for k in evaluation_k_values if k <= len(G)]
            if valid_k_values:
                from src.features._evaluation import compute_daily_evaluation_metrics

                eval_metrics = compute_daily_evaluation_metrics(
                    bad_actors=bad_actors_up_to_date,
                    k_values=valid_k_values,
                    pr_vol_deep=pr_vol_deep_scores,
                    pr_vol_shallow=pr_vol_shallow_scores,
                    pr_count=pr_count_scores,
                    hits_hub=hits_hubs,
                    hits_auth=hits_auths,
                    betweenness=betweenness_scores,
                    k_core=k_core_scores,
                )
                for algo_name, algo_metrics in eval_metrics.items():
                    metric_record: dict = {
                        "date": current_date.date(),
                        "algorithm": algo_name,
                        "total_nodes": algo_metrics["total_nodes"],
                        "total_fraud": algo_metrics["total_fraud"],
                        "fraud_rate": algo_metrics["fraud_rate"],
                        "roc_auc": algo_metrics.get("roc_auc"),
                        "average_precision": algo_metrics.get("average_precision"),
                    }
                    for k in valid_k_values:
                        metric_record[f"precision_at_{k}"] = algo_metrics["precision_at_k"].get(k)
                        metric_record[f"recall_at_{k}"] = algo_metrics["recall_at_k"].get(k)
                        metric_record[f"lift_at_{k}"] = algo_metrics["lift_at_k"].get(k)
                        metric_record[f"fraud_found_at_{k}"] = algo_metrics["fraud_found_at_k"].get(k)
                    eval_metric_records.append(metric_record)

    # ---- PageRank scores for sequential rank stability step ---------------
    pr_scores: dict = {
        node: feats.get("pagerank", 0.0)
        for node, feats in daily_metrics.get("pr_vol_deep", {}).items()
    }

    result = {
        "date": date_str,
        "features": features,
        "metrics": eval_metric_records,
        "pr_scores": pr_scores,
    }

    del G, day_edges, day_nodes, node_stats, daily_metrics
    gc.collect()

    return result


# ---------------------------------------------------------------------------
# Post-processing analysis
# ---------------------------------------------------------------------------

def _analyze_leiden_effectiveness(results_df: pd.DataFrame) -> None:
    print("\n" + "=" * 60)
    print("Leiden Community Detection Analysis")
    print("=" * 60)

    valid_df = results_df[results_df["leiden_id"] != -1].copy()
    if valid_df.empty:
        print("No valid Leiden communities found.")
        return

    last_date = valid_df["date"].max()
    final_df = valid_df[valid_df["date"] == last_date].copy()

    print(f"\nAnalysis based on final day: {last_date}")
    print(f"Total nodes with community assignment: {len(final_df):,}")

    n_communities = final_df["leiden_id"].nunique()
    print(f"Total communities detected: {n_communities:,}")

    community_stats = (
        final_df.groupby("leiden_id")
        .agg(
            size=("entity_id", "count"),
            fraud_count=("is_fraud", "sum"),
            fraud_rate=("is_fraud", "mean"),
        )
        .reset_index()
    )

    overall_fraud_rate = final_df["is_fraud"].mean()
    print(f"Overall fraud rate: {overall_fraud_rate:.4%}")

    print("\n[Community Size Distribution]")
    print("-" * 50)
    size_bins = [1, 2, 5, 10, 50, 100, 500, float("inf")]
    size_labels = ["1", "2-4", "5-9", "10-49", "50-99", "100-499", "500+"]

    community_stats["size_bin"] = pd.cut(
        community_stats["size"], bins=size_bins, labels=size_labels, right=False
    )

    size_analysis = (
        community_stats.groupby("size_bin", observed=True)
        .agg(
            n_communities=("leiden_id", "count"),
            total_nodes=("size", "sum"),
            total_fraud=("fraud_count", "sum"),
        )
        .reset_index()
    )

    size_analysis["fraud_rate"] = size_analysis["total_fraud"] / size_analysis["total_nodes"]
    size_analysis["lift"] = size_analysis["fraud_rate"] / overall_fraud_rate

    print(f"{'Size':<10} {'Communities':<12} {'Nodes':<10} {'Fraud':<8} {'Rate':<10} {'Lift':<8}")
    print("-" * 60)
    for _, row in size_analysis.iterrows():
        print(
            f"{row['size_bin']:<10} {int(row['n_communities']):<12} "
            f"{int(row['total_nodes']):<10} {int(row['total_fraud']):<8} "
            f"{row['fraud_rate']:.4%}   {row['lift']:.2f}x"
        )

    print("\n[Top 10 Communities by Fraud Rate (min 3 members)]")
    print("-" * 70)

    significant_communities = community_stats[community_stats["size"] >= 3].copy()
    top_fraud_communities = significant_communities.nlargest(10, "fraud_rate")

    print(f"{'Comm ID':<10} {'Size':<8} {'Fraud':<8} {'Rate':<12} {'Lift':<8}")
    print("-" * 50)
    for _, row in top_fraud_communities.iterrows():
        lift = row["fraud_rate"] / overall_fraud_rate if overall_fraud_rate > 0 else 0
        print(
            f"{int(row['leiden_id']):<10} {int(row['size']):<8} "
            f"{int(row['fraud_count']):<8} {row['fraud_rate']:.4%}      {lift:.2f}x"
        )

    pure_fraud_communities = community_stats[
        (community_stats["fraud_rate"] == 1.0) & (community_stats["size"] >= 2)
    ]

    if not pure_fraud_communities.empty:
        print("\n[Potential Fraud Rings: 100% Fraud Communities (size >= 2)]")
        print("-" * 50)
        print(
            f"Found {len(pure_fraud_communities)} communities that are 100% fraudulent"
        )
        print(
            f"Total nodes in these communities: "
            f"{pure_fraud_communities['size'].sum():,}"
        )
        print(
            f"Size distribution: {pure_fraud_communities['size'].describe().to_dict()}"
        )

    print("\n[Leiden Effectiveness Summary]")
    print("-" * 50)

    if "leiden_modularity" in valid_df.columns:
        mean_modularity = valid_df["leiden_modularity"].mean()
        print(f"Mean Leiden Modularity (Q): {mean_modularity:.4f}")


    small_community_threshold = 10
    small_communities = final_df[final_df["leiden_size"] <= small_community_threshold]
    fraud_in_small = small_communities["is_fraud"].sum()
    total_fraud = final_df["is_fraud"].sum()

    if total_fraud > 0:
        pct_fraud_in_small = fraud_in_small / total_fraud
        print(
            f"Fraud in small communities (size <= {small_community_threshold}): "
            f"{fraud_in_small:,} / {total_fraud:,} ({pct_fraud_in_small:.2%})"
        )

    avg_community_fraud_rate = community_stats["fraud_rate"].mean()
    print(f"Average community fraud rate: {avg_community_fraud_rate:.4%}")
    print(f"Overall fraud rate: {overall_fraud_rate:.4%}")

    high_fraud_communities = community_stats[
        community_stats["fraud_rate"] > overall_fraud_rate * 2
    ]
    if not high_fraud_communities.empty:
        fraud_in_high = high_fraud_communities["fraud_count"].sum()
        if total_fraud > 0:
            print(
                f"Fraud in high-concentration communities (>2x avg rate): "
                f"{fraud_in_high:,} / {total_fraud:,} "
                f"({fraud_in_high / total_fraud:.2%})"
            )


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 60)
    print("Graph Feature Generation Pipeline")
    print(f"Dataset: {DATASET_SIZE}")
    print(f"Evaluation:     {'Enabled' if RUN_EVALUATION else 'Disabled'}")
    print(f"Leiden:         {'Enabled' if RUN_LEIDEN else 'Disabled'}")
    print(f"Rank Stability: {'Enabled' if RUN_RANK_STABILITY else 'Disabled'}")
    print("=" * 60)

    # ======================================================================
    # 1. Scanning unique dates (Lazy Load)
    # ======================================================================
    edges_path = DATA_PATH / "aggregated_edges.parquet"
    nodes_path = DATA_PATH / "aggregated_nodes.parquet"

    print("Extracting unique temporal windows...")
    query_dates = (
        f"SELECT DISTINCT window_date "
        f"FROM read_parquet('{str(edges_path)}') "
        f"ORDER BY window_date"
    )
    unique_dates = duckdb.query(query_dates).df()["window_date"].tolist()
    print(f"Found {len(unique_dates)} windows to process.")

    # Load raw laundering data and accounts for ground truth labels
    print("Loading ground truth labels...")
    all_tx_df = pd.read_parquet(DATA_PATH / "1_filtered_transactions.parquet")
    accounts_df = pd.read_parquet(DATA_PATH / "2_filtered_accounts.parquet")
    
    laundering_df = all_tx_df[all_tx_df["is_laundering"] == 1].copy()
    del all_tx_df

    # Map from_account and to_account to actual Entity IDs
    laundering_df = laundering_df.merge(
        accounts_df, left_on="from_account", right_on="Account Number", how="inner"
    ).rename(columns={"Entity ID": "source_entity"}).drop(columns=["Account Number"])

    laundering_df = laundering_df.merge(
        accounts_df, left_on="to_account", right_on="Account Number", how="inner"
    ).rename(columns={"Entity ID": "target_entity"}).drop(columns=["Account Number"])

    # Safely convert PyArrow timestamps
    if pd.api.types.is_numeric_dtype(laundering_df["timestamp"]):
        laundering_df["timestamp"] = pd.to_datetime(laundering_df["timestamp"], unit="ns")
    else:
        laundering_df["timestamp"] = pd.to_datetime(laundering_df["timestamp"])

    laundering_df["timestamp"] = laundering_df["timestamp"].dt.tz_localize(None)

    # ======================================================================
    # 2. Pre-compute fraud labels per window date
    # ======================================================================
    print("Pre-computing per-window fraud labels...")
    date_bad_actors: dict[str, set] = {}
    for date_str in unique_dates:
        cutoff_dt = pd.to_datetime(date_str)
        mask = laundering_df["timestamp"] <= cutoff_dt
        laundering_txns = laundering_df.loc[mask]
        bad_actors: set = set()
        if "source_entity" in laundering_txns.columns:
            bad_actors = set(laundering_txns["source_entity"]).union(
                set(laundering_txns["target_entity"])
            )
        date_bad_actors[date_str] = bad_actors

    # Free memory
    del laundering_df, accounts_df

    # ======================================================================
    # 4. Parallel Map: ProcessPoolExecutor over temporal windows
    # ======================================================================
    run_flags_base: dict = {
        "run_evaluation": RUN_EVALUATION,
        "run_leiden": RUN_LEIDEN,
        "evaluation_k_values": list(EVALUATION_K_VALUES),
    }

    # Enforce strict sequential execution for large datasets to prevent OOM.
    max_workers = 6
    print(f"Launching ProcessPoolExecutor with {max_workers} workers...\n")

    collected_results: list[dict] = []

    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = {}
        for date_str in unique_dates:
            run_flags = {
                **run_flags_base,
                "bad_actors": date_bad_actors[date_str],
            }
            future = executor.submit(
                process_window,
                date_str,
                edges_path,
                nodes_path,
                run_flags,
            )
            futures[future] = date_str

        with tqdm(total=len(unique_dates), desc="Processing days", unit="day") as pbar:
            for future in as_completed(futures):
                try:
                    result = future.result()  # propagates worker exceptions
                    collected_results.append(result)
                except Exception as exc:
                    print(f"Day generated an exception: {exc}")
                pbar.update(1)

    # ======================================================================
    # 5. Sequential Reduce: Rank Stability Post-Processing
    #    (RankStabilityTracker is stateful — Day T depends on Day T-1)
    # ======================================================================
    print("\nApplying sequential rank stability post-processing...")

    # Sort chronologically so the tracker sees dates in order
    collected_results.sort(key=lambda r: r["date"])

    stability_tracker = RankStabilityTracker(
        top_k=RANK_STABILITY_TOP_K,
        threshold_percentile=RANK_ANOMALY_PERCENTILE,
    )

    all_rank_stability: list[dict] = []

    for result in collected_results:
        if RUN_RANK_STABILITY:
            stability_result = stability_tracker.compute(result["pr_scores"])

            if stability_result is not None:
                rank_changes: dict = stability_result["rank_changes"]
                anomalies: set = stability_result["anomalies"]

                all_rank_stability.append(
                    {
                        "date": pd.to_datetime(result["date"]).date(),
                        "algorithm": "pr_vol_deep",
                        "stability_score": stability_result["stability_score"],
                        "num_new_entrants": stability_result["num_new_entrants"],
                        "num_dropouts": stability_result["num_dropouts"],
                        "num_anomalies": stability_result["num_anomalies"],
                    }
                )

                # Patch the placeholder rank stability fields in each feature record
                for feat in result["features"]:
                    node = feat["entity_id"]
                    feat["pagerank_rank_change"] = rank_changes.get(node, 0)
                    feat["is_rank_anomaly"] = 1 if node in anomalies else 0

    # ======================================================================
    # 6. Flatten and compile final DataFrames
    # ======================================================================
    print("\nCompiling results...")

    all_features: list[dict] = []
    all_daily_metrics: list[dict] = []
    for result in collected_results:
        all_features.extend(result["features"])
        all_daily_metrics.extend(result["metrics"])

    results_df = pd.DataFrame(all_features)

    if results_df.empty:
        print("Warning: No features were generated!")
        return

    features_out = DATA_PATH / OUTPUT_FEATURES_FILE
    print(f"Saving features to {features_out}...")
    results_df.to_parquet(features_out, index=False)

    if RUN_EVALUATION and all_daily_metrics:
        metrics_df = pd.DataFrame(all_daily_metrics)
        metrics_path = DATA_PATH / OUTPUT_METRICS_FILE
        print(f"Saving metrics to {metrics_path}...")
        metrics_df.to_parquet(metrics_path, index=False)

        print("\n" + "=" * 60)
        print("Aggregate Evaluation Summary (Mean Across All Days)")
        print("=" * 60)

        for algo in ["pr_vol_deep", "pr_vol_shallow", "pr_count", "hits_hub", "hits_auth", "k_core", "betweenness"]:
            algo_df = metrics_df[metrics_df["algorithm"] == algo]
            if algo_df.empty:
                continue

            print(f"\n[{algo.upper()}]")
            print("-" * 40)

            mean_roc = float(algo_df["roc_auc"].mean())
            mean_ap = float(algo_df["average_precision"].mean())

            if not math.isnan(mean_roc):
                print(f"  Mean ROC-AUC:            {mean_roc:.4f}")
            if not math.isnan(mean_ap):
                print(f"  Mean Average Precision:  {mean_ap:.4f}")

            print("\n  Mean Precision@K:")
            for k in EVALUATION_K_VALUES:
                col = f"precision_at_{k}"
                if col in algo_df.columns:
                    mean_prec = float(algo_df[col].mean())
                    if not math.isnan(mean_prec):
                        lift_col = f"lift_at_{k}"
                        mean_lift = (
                            float(algo_df[lift_col].mean())
                            if lift_col in algo_df.columns
                            else 0.0
                        )
                        print(f"    @{k:>5}: {mean_prec:.4%} (lift: {mean_lift:.2f}x)")

    if RUN_LEIDEN:
        leiden_analysis_df = results_df.rename(
            columns={
                "leiden_macro_id": "leiden_id",
                "leiden_macro_size": "leiden_size",
                "leiden_macro_modularity": "leiden_modularity",
            }
        )
        _analyze_leiden_effectiveness(leiden_analysis_df)

    print("\n" + "=" * 60)
    print("Feature Statistics Summary")
    print("=" * 60)
    summary_cols = [
        "pr_vol_deep",
        "pr_vol_shallow",
        "pr_count",
        "hits_hub",
        "hits_auth",
        "betweenness",
        "k_core",
        "degree",
        "vol_sent",
        "vol_recv",
        "tx_count",
        "time_variance",
        "flow_ratio",
        "pagerank_rank_change",
    ]
    if RUN_LEIDEN:
        summary_cols += ["leiden_macro_size", "leiden_micro_size", "leiden_macro_modularity", "leiden_micro_modularity"]

    print(results_df[[c for c in summary_cols if c in results_df.columns]].describe())

    if RUN_RANK_STABILITY and results_df["is_rank_anomaly"].sum() > 0:
        print("\n" + "=" * 60)
        print("Rank Anomaly Analysis (reference: pr_vol_deep)")
        print("=" * 60)
        anomaly_df = results_df[results_df["is_rank_anomaly"] == 1]
        fraud_in_anomalies = anomaly_df["is_fraud"].sum()
        total_anomaly_flags = len(anomaly_df)
        overall_fraud_rate = results_df["is_fraud"].mean()
        anomaly_fraud_rate = (
            anomaly_df["is_fraud"].mean() if total_anomaly_flags > 0 else 0
        )

        print(f"Total rank anomaly flags: {total_anomaly_flags:,}")
        print(
            f"Fraud among rank anomalies: {fraud_in_anomalies:,} "
            f"({anomaly_fraud_rate:.2%})"
        )
        print(f"Overall fraud rate: {overall_fraud_rate:.2%}")
        if overall_fraud_rate > 0:
            print(
                f"Lift from rank anomaly detection: "
                f"{anomaly_fraud_rate / overall_fraud_rate:.2f}x"
            )

    print("\nDone!")


if __name__ == "__main__":
    main()
